<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="StreamingPlatform" nsURI="https://any.com" nsPrefix="SP">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Auditable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdAt" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatedAt" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tenure" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="donationAmout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unlockCondition" unique="false"
        lowerBound="1" eType="#//UnlockCondition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnlockCondition">
    <eLiterals name="DonationAmount"/>
    <eLiterals name="Tenure" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Badge" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badgeID" eType="#//UUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="UUID" instanceClassName="java.util.UUID"/>
  <eClassifiers xsi:type="ecore:EClass" name="MediaContent" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tags" unique="false" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewCount" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Category">
    <eLiterals name="Videogames"/>
    <eLiterals name="JustChatting" value="1"/>
    <eLiterals name="Esports" value="2"/>
    <eLiterals name="Sports" value="3"/>
    <eLiterals name="TalkShowsAndPodcasts" value="4"/>
  </eClassifiers>
</ecore:EPackage>
